GET http://localhost:3000/api/categories
X-API-Key: RAHASIA
Accept: application/json

### Create
POST http://localhost:3000/api/categories
X-API-Key: RAHASIA
Accept: application/json
Content-Type: application/json

{
  "name" : "Milk"
}

### get by id
GET http://localhost:3000/api/categories/12
X-API-Key: RAHASIA
Accept: application/json


### update
PUT http://localhost:3000/api/categories/12
X-API-Key: RAHASIA
Accept: application/json
Content-Type: application/json

{
  "name" : "Milkshake"
}

### delete by id
DELETE http://localhost:3000/api/categories/11
X-API-Key: RAHASIA
Accept: application/json